import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { projectId, branchName, message } = body;

    if (!projectId || !branchName) {
      return NextResponse.json({ error: 'Missing projectId or branchName' }, { status: 400 });
    }

    const project = await prisma.project.findUnique({
      where: { id: projectId },
    });

    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }

    const settings = project.settings as { discordDevWebhookUrl?: string } | null;
    const webhookUrl = settings?.discordDevWebhookUrl;

    if (!webhookUrl) {
      return NextResponse.json({ 
        success: false, 
        message: 'No discordDevWebhookUrl configured for this project' 
      }, { status: 200 });
    }

    // Fire webhook
    await fetch(webhookUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        content: null,
        embeds: [
          {
            title: "🚀 New UI Spec Branch Ready",
            description: message || "A new feature branch has been generated by the AI Tech-Lead and is ready for development.",
            color: 3447003, // Blue
            fields: [
              {
                name: "Project",
                value: project.name,
                inline: true
              },
              {
                name: "Branch",
                value: `\`${branchName}\``,
                inline: true
              }
            ],
            timestamp: new Date().toISOString()
          }
        ]
      }),
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error notifying devs:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
