// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { existsSync } from "node:fs";
import path from "node:path";
import { defineConfig } from "prisma/config";

// Local setups keep one .env at the repo root, and `pnpm --filter` runs Prisma
// from packages/core. Variables that are already set always win.
const rootEnv = path.resolve(process.cwd(), "../../.env");
if (existsSync(rootEnv)) process.loadEnvFile(rootEnv);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
